[package]
name = "tv"
version = "0.1.0"
authors = ["alexhallam <alexhallam6.28@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.14.1"
tabwriter = "1.2.1"
owo-colors = "1.3.0"
pad = "0.1"
regex = "1.4.5"
csv = "*"
structopt= "*"
itertools= "*"
